if channelKicker.setting.language == "german" then
        kickMSG = "Persona non grata!"
        kickMSGFag = "Persona non grata!"
        kickMSGdefaultChan = "Dieser Channel darf nicht als Standardchannel betreten werden!"
        kickMSGConnects = "Du brauchst mehr Verbindungen!"
        kickMSGServerGroup = "Du hast eine nicht erwünschte Servergruppe!"
        kickMSGrecord = "Du darfst in diesem Channel nicht aufnehmen!!"
        kickMSGts3server = "Du darfst hier keine ts3server:// links senden!"
        kickMSGipadress = "Du darfst hier keine IP's versenden!"
        kickMSGfreeze = "Hat versucht Clients einzufrieren!!!!"
        kickMSGclear = "Hat versucht den Channelchat zu leeren!!!"
		kickMSGbadname = "Unerwuenschter Nickname!"
		kickMSGOutputMuted = "Du wurdest gekickt weil deine Lautsprecher gemuted sind."
		kickMSGAway = "Du wurdest gekickt weil du AFK bist."
		kickMSGIdle = "Du warst zu lange untätig!"
		kickMSGBadWord = "Bitte keine Beleidigungen"
		kickMSGLink = "Du darfst hier keine Links versenden!"
		kickMSGbadOS = "Dein Betriebssystem "
		kickMSGbadOS2 = " ist hier nicht erwünscht!"
		kickMSGbadCountry = "Dein Land "
		kickMSGbadCountry2 = "ist hier nicht erwünscht!"
		kickMSGblocked = "Du bist geblockt!"
		kickMSGspam = "Du darfst dieselbe Nachricht nicht zweimal wiederholen!"
		tp_req_MSG = "Ich haette gerne Talk-Power"
		antifloodMSG = "CK: Aktion werden aufgrund von Antiflood zurückgehalten!"
        channelMSG = "\n-= Dieser Channel wird gesichert durch das channelKicker Script von Chriis und Bluscream =-"
        channelMSG_e = "Verbotene Aktionen:\nEine Aufnahme in diesem Channel zu starten!\nWährend einer Aufnahme in diesen Channel zu joinen!\nDirekt in diesen Channel zu verbinden!\nts3server Links zu senden!\nIP's zu versenden!\nClients abstürzen zu lassen!\nDen Channelchat zu leeren!\nMit der ersten Verbindung zu joinen!\nMit geblacklisteten Nicknamen zu joinen!\nMit bestimmten Servergruppen zu joinen!\nLinks in diesem Channel zu versenden!\nBöse Wörter in die Hand zu nehmen!"
else
        kickMSG = "Persona non grata!"
        kickMSGFag = "Persona non grata!"
        kickMSGdefaultChan = "Dont use default channel to join here!"
        kickMSGConnects = "You need more Connections!"
        kickMSGServerGroup = "Your Server Groups are not allowed'!"
        kickMSGrecord = "Dont record in this Channel!"
        kickMSGts3server = "Dont send ts3server links in this Channel!"
        kickMSGipadress = "Dont send ip adresses in this Channel!"
        kickMSGfreeze = "Has attempted to freeze clients!!!!"
        kickMSGclear = "Has attempted to clear everyone's chat!!!"
		kickMSGbadname = "Bad Nickname!"
		kickMSGOutputMuted = "You were kicked for muting your speakers."
		kickMSGAway = "You were AFK to long."
		kickMSGIdle = "You were idling to long!"
		kickMSGBadWord = "Please no bad words here"
		kickMSGLink = "Dont send URLs in here!"
		kickMSGbadOS = "Your Operating system "
		kickMSGbadOS2 = " is not allowed here!"
		kickMSGbadCountry = "Your Country "
		kickMSGbadCountry2 = " is not allowed here!"
		kickMSGblocked = "You are blocked!"
		kickMSGspam = "You are not allowed to repeat the same message!"
		tp_req_MSG = "I want Talk-Power"
		antifloodMSG = "CK: Not doing anything cause we have antiflood triggered!"
        channelMSG = "\n-= I am protecting you're channel with the channelKicker Script =-"
        channelMSG_e = "Some actions are not allowed:\nStarting to record in this channel!\nJoining this channel while recording!\nConnecting here via default channel\nSending ts3server:// links in this channel\nSending IP's in this channel!\nFreezing Clients\nClearing the Channel chat!\nJoin on the first connection!\nJoin with a blacklisted nickname!\nJoin with blocked server groups!\nSend Links in this channel\nSend bad words here"
end
channelKicker.info.MODULEFILE = "lang"
ts3.printMessageToCurrentTab("Loaded "..channelKicker.info.MODULE.." v"..channelKicker.info.MODULEVERSION.." by "..channelKicker.info.MODULEAUTHOR.." from "..ts3.getPluginPath().."lua_plugin/"..channelKicker.info.MODULEFOLDER.."/"..channelKicker.info.MODULEFILE.."."..channelKicker.info.MODULEEXT)